name: scan with checkov
permissions:
  actions: read
  contents: read
  security-events: write  # ← REQUIRED to upload SARIF files



on: 
  push:
  workflow_call:
  pull_request:
  
jobs: 
  checkov_scan:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: checkout custom policy repo
        uses: actions/checkout@v4
        with:
          repository: melissa-commits/checkov_policy_ex
          path: policies


      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: install checkov
        run: pip install checkov

      - name: run scan
        run: checkov -d . --external-checks-dir policies --output-file-path ./results.sarif -o sarif -o cli

      - name: upload results
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
